export github_email="asad.mahmood@educative.io"
export github_user="asadhky"
export access_token="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"
export github_repo="https://github.com/asadhky/fifth.git"
export filename="fifth"
export reponame="abcd"
export EDUCATIVE_LIVE_VM_URL="https://ed-6436638368727040_dc.educative.run"